# Generated by Django 3.1.7 on 2021-03-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('city_code', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
            ],
        ),
    ]
