# Generated by Django 3.1.7 on 2021-03-07 07:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=11)),
                ('zip_code', models.CharField(max_length=20)),
                ('city', models.ManyToManyField(to='city.City')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
